---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, AFX, FAS, ASA, all-flash, ONTAP 
summary: ネットアップのONTAPファミリーストレージシステムは、管理が容易で高速かつセキュアなストレージを必要とするエンタープライズアプリケーション向けに設計されており、エンタープライズクラスの信頼性と継続的なデータアクセスを備えています。 
---
= ONTAPハードウェアシステムの詳細
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ネットアップのONTAPハードウェアシステムは、管理が容易で高速かつセキュアなストレージを必要とするエンタープライズアプリケーション向けに設計されており、エンタープライズクラスの信頼性と継続的なデータアクセスを備えています。

NetApp のONTAPハードウェア システムは、オールフラッシュ、ハイブリッド フラッシュ、HDD のみの構成で提供されており、パフォーマンス、容量、コストの要件に最適なストレージ メディア ミックスを選択できます。

さまざまなモデルを組み合わせてクラスタを構成し、同じストレージシステムで混在ワークロードを実行したり、最新テクノロジを搭載した新世代のストレージを追加して環境を構築したりできます。



== オールフラッシュFAS （AFF ）システム

NVMeベースのAFF システムは、仮想環境向けに構築された堅牢なスケールアウトプラットフォームであり、独立したシステムとして導入することも、NetApp ONTAP 構成のハイパフォーマンス階層として導入することもできます。

ハイパフォーマンス、低レイテンシ、信頼性を必要とするVDIやデータベースなど、さまざまなワークロードに対応できるオールフラッシュFAS 構成は、ビジネスクリティカルなアプリケーションに最適です。

* https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF Aシリーズのデータシートを読む"^]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF Cシリーズのデータシートを読む"^]




== AFX

NetApp AFX は、並列ファイルシステムとニッチな AI ストレージソリューションのパフォーマンス上の利点をすべて、シンプルかつ安全で完全に統合されたエンタープライズグレードのプラットフォーム上で実現する、エンタープライズグレードの分散型オールフラッシュ ストレージ システムです。

* https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["AFXデータシートを読む"^]
* https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["AFXストレージについて詳しくはこちら"^]




== オールフラッシュSANアレイ（ASA）システム

NetAppオールフラッシュSANアレイ（ASA）は、SAN専用のシンプルなエクスペリエンスを提供し、FCPまたはiSCSIプロトコルを使用して、エンタープライズのミッションクリティカルなデータベースやその他のSANワークロードに継続的なデータ可用性を提供します。

.ASA r2システム
新しいNetApp ASA r2 システム (ASA A1K、 ASA A70、 ASA A90、 ASA A20、 ASA A30、 ASA A50、C30) は、SAN のみを利用するお客様のニーズに合わせた簡素化されたエクスペリエンスを実現する、統合されたハードウェアおよびソフトウェア ソリューションを提供します。

ASA R2システムでは、ONTAPソフトウェアとSystem Managerが合理化され、SAN環境でサポートされていない機能が可視化されます。

* https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASAのデータシートを読む"^]
* 詳細については、link:https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html["新しいASA R2システムとASAシステムの比較"^]
* ASAおよびASA R2システムの構成の完全なサポートと制限事項については、を参照してください。 https://hwu.netapp.com/["NetApp Hardware Universe"^]




== FAS ハイブリッドフラッシュシステム

FAS ハイブリッドフラッシュシステムは、SANとNASの共有/統合環境向けに構築されたハードウェアプラットフォームで、充実のデータ管理と容易なクラウド接続を必要とします。

FAS ハイブリッドフラッシュシステムは、可用性に優れたハードウェアを搭載し、フラッシュと従来の回転式ドライブの理想的な組み合わせを組み合わせることで、ワークロードのニーズに対費用効果の高い方法で応えることができます。バックアップと保持、一般的なビジネスアプリケーションの統合、分散コンテンツに最適です。

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FASのデータシートを読む"^]



== MetroCluster

ONTAPのMetroCluster機能を使用して構成されたONTAPのハードウェアストレージシステムは、アレイベースのクラスタリングと同期レプリケーションを組み合わせて、継続的な可用性を実現し、データ損失をゼロにする解決策を提供します。MetroCluster 構成では、ミッションクリティカルなデータをトランザクション単位で瞬時に複製し、アプリケーションやデータへの中断のないアクセスを実現します。

MetroCluster は、標準的なデータレプリケーションソリューションとは異なり、ホスト環境とシームレスに連携して継続的なデータ可用性を実現します。複雑なフェイルオーバースクリプトを作成して管理する必要はありません。

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["MetroClusterの詳細はこちら"^]



== ONTAP ソフトウェア

ONTAPデータ管理ソフトウェアは、ONTAPハードウェアシステムに搭載されるクラスタ化されたストレージソフトウェアです。ONTAPソフトウェアは、あらゆるタイプのハードウェアノードを最大24個サポートするグローバルネームスペースを備えており、ユニファイドストレージ（ブロックおよびファイル）をサポートしているため、ONTAP System Manager GUIを使用して管理できるワークロードを大幅に統合できます。

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["ONTAPソフトウェアのデータシートを読む"^]

.を参照してください。
* https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAPハードウェアシステムのドキュメント"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster のドキュメント"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP のドキュメント"^]

