---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, all-flash, ONTAP 
summary: NetApp ONTAP ストレージシステムファミリーは、エンタープライズクラスの信頼性と継続的なデータアクセスを備えた、管理が容易で、高速でセキュアなストレージを必要とするエンタープライズアプリケーション向けに設計されています。 
---
= AFF およびFAS ファミリーのストレージシステムについて説明します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


NetApp AFF and FAS ストレージシステムファミリーは、エンタープライズクラスの信頼性と継続的なデータアクセスを備えた、管理が容易で、高速でセキュアなストレージを必要とするエンタープライズアプリケーション向けに設計されています。

AFF システムとFAS システムは、オールフラッシュ（AFF ）構成とハイブリッドフラッシュ構成およびHDDのみ（FAS ）構成が用意されており、パフォーマンス、容量、コストの要件に最も適した組み合わせのストレージメディアを選択できます。

AFF モデルとFAS モデルをさまざまに組み合わせてクラスタ化することで、同じストレージシステム上で混在ワークロードを実行し、最新テクノロジを搭載した新世代のストレージを追加することで環境を構築できます。



== オールフラッシュFAS （AFF ）システム

NVMeベースのAFF システムは、仮想環境向けに構築された堅牢なスケールアウトプラットフォームであり、独立したシステムとして導入することも、NetApp ONTAP 構成のハイパフォーマンス階層として導入することもできます。

ハイパフォーマンス、低レイテンシ、信頼性を必要とするVDIやデータベースなど、さまざまなワークロードに対応できるオールフラッシュFAS 構成は、ビジネスクリティカルなアプリケーションに最適です。

https://["AFF Aシリーズのデータシートをご覧ください"^] および https://["AFF Cシリーズのデータシートをご覧ください"^]。



== FAS ハイブリッドフラッシュシステム

FAS ハイブリッドフラッシュシステムは、SANとNASの共有/統合環境向けに構築されたハードウェアプラットフォームで、充実のデータ管理と容易なクラウド接続を必要とします。

FAS ハイブリッドフラッシュシステムは、可用性に優れたハードウェアを搭載し、フラッシュと従来の回転式ドライブの理想的な組み合わせを組み合わせることで、ワークロードのニーズに対費用効果の高い方法で応えることができます。バックアップと保持、一般的なビジネスアプリケーションの統合、分散コンテンツに最適です。

https://["FAS のデータシートをご覧ください"^]



== MetroCluster

AFF およびFAS ストレージシステムにONTAPのMetroCluster 機能を組み合わせて使用すると、アレイベースのクラスタリングと同期レプリケーションを組み合わせた解決策 が提供され、継続的な可用性を実現し、データ損失をゼロにすることができます。MetroCluster 構成では、ミッションクリティカルなデータをトランザクション単位で瞬時に複製し、アプリケーションやデータへの中断のないアクセスを実現します。

MetroCluster は、標準的なデータレプリケーションソリューションとは異なり、ホスト環境とシームレスに連携して継続的なデータ可用性を実現します。複雑なフェイルオーバースクリプトを作成して管理する必要はありません。

https://["MetroCluster の詳細については、こちらをご覧ください"^]



== ONTAP ソフトウェア

ONTAP データ管理ソフトウェアは、AFF およびFAS システムを強化するクラスタストレージソフトウェアです。AFF ノードとFAS ノードを24個までサポートするグローバルネームスペースをすべてのタイプで使用できるONTAP ソフトウェアはユニファイドストレージ（ブロックとファイル）をサポートしているため、ONTAP System Manager GUIで管理可能なワークロードを大幅に統合することができます。

https://["ONTAP のデータシートをご覧ください"^]。



== を参照してください。

* https://["AFF およびFAS のドキュメント"^]
* https://["MetroCluster のドキュメント"^]
* https://["ONTAP のドキュメント"^]

