---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, ASA, all-flash, ONTAP 
summary: ネットアップのONTAPファミリーストレージシステムは、管理が容易で高速かつセキュアなストレージを必要とするエンタープライズアプリケーション向けに設計されており、エンタープライズクラスの信頼性と継続的なデータアクセスを備えています。 
---
= ONTAPハードウェアシステムの詳細
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


ネットアップのONTAPハードウェアシステムは、管理が容易で高速かつセキュアなストレージを必要とするエンタープライズアプリケーション向けに設計されており、エンタープライズクラスの信頼性と継続的なデータアクセスを備えています。

ネットアップのONTAPハードウェアシステムには、オールフラッシュ（AFF）構成とハイブリッドフラッシュとHDDのみ（FAS）構成があり、パフォーマンス、容量、コストの各要件に最適なストレージメディアの組み合わせを選択できます。

さまざまなモデルを組み合わせてクラスタを構成し、同じストレージシステムで混在ワークロードを実行したり、最新テクノロジを搭載した新世代のストレージを追加して環境を構築したりできます。



== オールフラッシュFAS （AFF ）システム

NVMeベースのAFF システムは、仮想環境向けに構築された堅牢なスケールアウトプラットフォームであり、独立したシステムとして導入することも、NetApp ONTAP 構成のハイパフォーマンス階層として導入することもできます。

ハイパフォーマンス、低レイテンシ、信頼性を必要とするVDIやデータベースなど、さまざまなワークロードに対応できるオールフラッシュFAS 構成は、ビジネスクリティカルなアプリケーションに最適です。

https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF Aシリーズのデータシートをご覧ください"^] および https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF Cシリーズのデータシートをご覧ください"^]。



== オールSANアレイ（ASA）システム

NetAppオールフラッシュSANアレイ（ASA）は、SAN専用のシンプルなエクスペリエンスを提供し、FCPまたはiSCSIプロトコルを使用して、エンタープライズのミッションクリティカルなデータベースやその他のSANワークロードに継続的なデータ可用性を提供します。

https://www.netapp.com/pdf.html?item=/media/19466-SB-4081.pdf["ASAのデータシートを読む"^]



== FAS ハイブリッドフラッシュシステム

FAS ハイブリッドフラッシュシステムは、SANとNASの共有/統合環境向けに構築されたハードウェアプラットフォームで、充実のデータ管理と容易なクラウド接続を必要とします。

FAS ハイブリッドフラッシュシステムは、可用性に優れたハードウェアを搭載し、フラッシュと従来の回転式ドライブの理想的な組み合わせを組み合わせることで、ワークロードのニーズに対費用効果の高い方法で応えることができます。バックアップと保持、一般的なビジネスアプリケーションの統合、分散コンテンツに最適です。

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS のデータシートをご覧ください"^]



== MetroCluster

ONTAPのMetroCluster機能を使用して構成されたONTAPのハードウェアストレージシステムは、アレイベースのクラスタリングと同期レプリケーションを組み合わせて、継続的な可用性を実現し、データ損失をゼロにする解決策を提供します。MetroCluster 構成では、ミッションクリティカルなデータをトランザクション単位で瞬時に複製し、アプリケーションやデータへの中断のないアクセスを実現します。

MetroCluster は、標準的なデータレプリケーションソリューションとは異なり、ホスト環境とシームレスに連携して継続的なデータ可用性を実現します。複雑なフェイルオーバースクリプトを作成して管理する必要はありません。

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["MetroCluster の詳細については、こちらをご覧ください"^]



== ONTAP ソフトウェア

ONTAPデータ管理ソフトウェアは、ONTAPハードウェアシステムに搭載されるクラスタ化されたストレージソフトウェアです。ONTAPソフトウェアは、あらゆるタイプのハードウェアノードを最大24個サポートするグローバルネームスペースを備えており、ユニファイドストレージ（ブロックおよびファイル）をサポートしているため、ONTAP System Manager GUIを使用して管理できるワークロードを大幅に統合できます。

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["ONTAP のデータシートをご覧ください"^]。



== を参照してください。

* https://docs.netapp.com/us-en/ontap-systems/index.html["AFF およびFAS のドキュメント"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster のドキュメント"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP のドキュメント"^]

